# Generated by Django 5.2.3 on 2025-07-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário responsável pela barbearia', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário responsável pela barbearia', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_barbearia', to=settings.AUTH_USER_MODEL),
        ),
    ]
