# Generated by Django 5.2.3 on 2025-07-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_administrador_usuario_barbearia_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pela barbearia', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pela barbearia', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_barbearia', to=settings.AUTH_USER_MODEL),
        ),
    ]
