# Generated by Django 5.2.3 on 2025-07-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_agendamento_usuario_barbeiro_usuario_cliente_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo administrador', on_delete=django.db.models.deletion.CASCADE, related_name='administrador_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pela barbearia', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_barbearia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo barbeiro', on_delete=django.db.models.deletion.CASCADE, related_name='barbeiro_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo endereço', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_endereco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo pagamento', on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo serviço', on_delete=django.db.models.deletion.CASCADE, related_name='servico_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
